[tool.poetry]
name = "matrix-loading"
version = "0.1.0"
description = "Data analysis tool for Matrix resistance fighters"
authors = ["Neo <neo@zion.net>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.0"
numpy = "^1.24.0"
matplotlib = "^3.7.2"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"